### PR TITLE
Issue43

### LINKED ISSUE #43: Make header nav dynamic.
Open current nav and show horizontal nav based on current page

### PR DESCRIPTION
**Pull request by hsaginor**
Fix #43 

Test URLs:
- Before: https://v2--helix-sportsmagazine--headwirecom.hlx.page/
- After: https://issue43--helix-sportsmagazine--headwirecom.hlx.page/

### CODE REVIEW

**Comment by hsaginor** [comment]
@icaraps 
I am not sure why https://issue43--helix-sportsmagazine--headwirecom.hlx.page/blocks/header/leaderboard.js returns 404. The file exists in this branch https://github.com/headwirecom/helix-sportsmagazine/tree/issue43/blocks/header

**Comment by icaraps** [comment]
There was probably a sync issue on hlx side. I updated the code bus manually with https://www.hlx.live/docs/admin.html#tag/code/operation/updateCode and it's in sync now.

**Comment by icaraps** [comment]
Looks cool ! How should the navigation behave for the root page ? 
Currently it looks like this one the official site: 
Screenshot 2023-06-05 at 10 50 07

**Comment by hsaginor** [comment]
> Looks cool ! How should the navigation behave for the root page ? Currently it looks like this one the official site: Screenshot 2023-06-05 at 10 50 07

I added the horizontal subnav on the home page. I think other visual changes we should handle as a separate issue when we address the homepage and landing pages. We might want to discuss that with Erin and William as well.

**Comment by icaraps** [comment]
> I think other visual changes we should handle as a separate issue when we address the homepage and landing pages

Sounds good to me

**Review by icaraps — APPROVED** [review]

**Pull request merged**
