### PR TITLE
Fix lint

### LINKED ISSUE #32: Fix linting issues.

### PR DESCRIPTION
**Pull request by hsaginor**
Fix #32

Test URLs:
- Before: [https://main--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/equipment/products/2022/03/linksoul-sunflower-of-peace-charity-tee](https://main--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/equipment/products/2022/03/linksoul-sunflower-of-peace-charity-tee)
- After: [https://fixLint--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/equipment/products/2022/03/linksoul-sunflower-of-peace-charity-tee](https://fixLint--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/equipment/products/2022/03/linksoul-sunflower-of-peace-charity-tee)
- Before: [https://main--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/instruction/_default/article/2021/10/desert-golf-how-to-play](https://main--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/instruction/_default/article/2021/10/desert-golf-how-to-play)
- After: [https://fixLint--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/instruction/_default/article/2021/10/desert-golf-how-to-play](https://fixLint--helix-sportsmagazine--headwirecom.hlx.page/import-test/play/instruction/_default/article/2021/10/desert-golf-how-to-play)

### CODE REVIEW

**Comment by icaraps** [comment]
There are still a bunch of linting issues https://github.com/headwirecom/helix-sportsmagazine/actions/runs/4868613256/jobs/8682244077?pr=33

There should be a green check here. 
Screenshot 2023-05-03 at 10 57 55

**Comment by icaraps** [comment]
@hsaginor I tried to solve most linting issues. There are still some namely: 
1. console.log statements (not sure what you want to do with it. You can also disable the rule if you want. Up to you ...)
2. dependency cycle issues (this one needs more refactoring so module A doesn't import module B and vice versa)

**Comment by hsaginor** [comment]
> @hsaginor I tried to solve most JS linting issues. There are still some namely:
> 
> 1. console.log statements (not sure what you want to do with it. You can also disable the rule if you want. Up to you ...)
> 2. dependency cycle issues (this one needs more refactoring so module A doesn't import module B and vice versa)
> 
> Didn't fix the CSS issues yet... Working on it ...

So, the fixes in this PR are after I pulled your code that was already merged and it didn't include code any code that was still in PRs as of yesterday.

**Comment by icaraps** [comment]
I believe CLS can be improved by moving CLS specific block CSS into global styles.css

**Pull request merged**
